### ISSUE TITLE
Add back the simulation code

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/token-factory#1]
currently `x/tokenfactory/module.go` has relevant lines commented out and `x/tokenfactory/simulation` is all commented out. It depended on a lot of Osmosis-specific stuff. Need to figure out how to get this working... and I have little experience with sims

**Comment by GNaD13** [comment]
Hi @ethanfrey , Can I take this issue?

**Comment by ethanfrey** [comment]
Please do. 
This was the old code https://github.com/CosmWasm/token-factory/tree/main/x/tokenfactory/simulation which I commented out.

I would appreciate help getting it working.
